import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Select from "../components/Select";
import FormikContainer from "../components/FormikContainer";
import CheckBoxText from "../components/CheckBoxTest";

export default function Home() {
  const [year, setYear] = useState();
  const [moviesList, setMoviesList] = useState([]);
  const [sucess, setSuccess] = useState(false);
  const API = "https://jsonmock.hackerrank.com/api/movies?year";

  const searchYear = async (e) => {
    if (year != "") {
      const res = await fetch(`${API}=${year}`);
      const movies = await res.json();
      setMoviesList(movies.data);
      setSuccess(true);
      console.log(movies.list, "movies.list");
    } else {
      setSuccess(false);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>List Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          onChange={(e) => setYear(e.target.value)}
          value={year}
          type="number"
        />
        <button onClick={searchYear} data-testid="submit-button">
          Search
        </button>
        {sucess && (
          <ul>
            {moviesList.length > 0 ? (
              moviesList.map((movie) => (
                <li key={movie.imdbID} className={styles.list}>
                  {movie.Title}
                </li>
              ))
            ) : (
              <li>No movies found</li>
            )}
          </ul>
        )}
      </div>
      <div>
        <Select />
      </div>
      <div>
        <FormikContainer />
      </div>
      <div>
        <CheckBoxText />
      </div>
    </div>
  );
}
